/// Flutter icons Flutter_custom_icon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Flutter_custom_icon
///      fonts:
///       - asset: fonts/Flutter_custom_icon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class Flutter_custom_icon {
  Flutter_custom_icon._();

  static const _kFontFam = 'Flutter_custom_icon';

  static const IconData cog_alt = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData videocam = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData thermometer = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData temperatire = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData lamp = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData light_down = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData light_up = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData windows = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData autorenew = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData enter = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData gamepad = const IconData(0xf11b, fontFamily: _kFontFam);
  static const IconData chart_line = const IconData(0xf201, fontFamily: _kFontFam);
}
