name: flutterapp
description: A Home Automation Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view:

  # Http library dependency
  http:

  # mqtt_client library dependency
  mqtt_client: ^5.6.2

  # wifi configuration library
  wifi_configuration: ^1.2.1

  # google assistance voice  recognition
  speech_recognition: ^0.3.0+1

  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^1.2.2

  # Run a thread on background
  background_fetch: ^0.5.4
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

# To run flutter packages pub run flutter_launcher_icons:main 
flutter_icons:
  android: true
  ios: true
  image_path: "statics/images/flutter.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add fonts to your application, add an fonts section, like this:
  fonts:
    - family:  Flutter_custom_icon
      fonts:
       - asset: statics/fonts/Flutter_custom_icon.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - statics/images/flutter.png
    - statics/images/home_logo.jpg
    - statics/images/devices.png
    - statics/images/outdoor.jpg
    - statics/images/indoor.jpg
    - statics/icons/statistics.png
    - statics/icons/remote_control.jpg
    - statics/icons/configuration.png
  #  - images/a_dot_ham.jpeg
    #- statics/cert/AmazonRootCA1.pem
    #- statics/cert/3a763a4f22-certificate.pem.crt
    #- statics/cert/3a763a4f22-private.pem.key
    #- statics/cert/3a763a4f22-public.pem.key

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
